### ISSUE TITLE
QUESTION: 2 Contact sensors

### ISSUE THREAD

**Issue by iondarie** [plhyhc/homebridge-garage-door-wsensor#1]
Hello,

My gate has 2 magnetic switches, 1 at each end of the gate to see when it is open or closed.

Can the script be modified to use 2 magnetic switches? 

Thank you,

**Comment by plhyhc** [comment]
Hello, you should be able to modify the code to allow for more than one sensor.  You would have to update the checkSensor() function in the index.js file.  That function at the moment is only checking 1 pin.  You would just have to expand it to check 2 pins.   Hope that helps.
