### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by toshibochan** [plhyhc/homebridge-garage-door-wsensor#10]
Have bug or missing code.
Usually when Door is close Siri or sene don’t trigger the relay but your code is triggering the relay. Last night I did good night sene and open my gate and garage.

**Comment by toshibochan** [comment]
Have to add code when is open and ask to open don’t trigger the relay. And when is closed and ask to close don’t trigger the relay.

**Comment by mfw2010** [comment]
I have the same issue, got around it by using shortcuts to capture my Siri phrases and added conditions, however shortcuts requires phone to be unlocked which is a little annoying.

**Comment by plhyhc** [comment]
@mfw2010 Thanks for sharing.  I am curious about these shortcuts and would like to know more about them.  Are these added in code or in iOS?  If in code would you mind sharing?  And yes I know what you mean about needed to have your phone unlocked to open/close the garage door, but I understand it is a security feature from Apple.
