### ISSUE TITLE
Sensor

### ISSUE THREAD

**Issue by spalda8** [plhyhc/homebridge-garage-door-wsensor#11]
Hello, I would like to ask if it is possible to add 2 sensors, one would define an open gate and the other a closed gate. At the same time, I would like to ask if it is possible to use a wireless sensor, if so, how and what type.

**Comment by plhyhc** [comment]
Hello, this npm package already has 1 sensor to detect when the door is
open or closed.  But if you wanted to add another sensor you would need to
clone or fork the project to add the ability to monitor another sensor for
when the door is finished opening. You would have to test the homebridge
API door states to handle closed, opening, and open. Regarding the sensors
I use a pair of long wires to and from the sensor to the Pi.  I am not sure
if wireless would be an option as I have no experience with that.
