### ISSUE TITLE
Separated for open and close the garage door

### ISSUE THREAD

**Issue by serial8killer** [plhyhc/homebridge-garage-door-wsensor#14]
Hey guys, first of all great work in the plug in.
I've been using this plug for a couple of years now and been working great on an outside garage door.

The issue is that I have another garage door that I also want to put a raspberry pie and automate, but the unit uses different contacts for open and to close the garage door (shorting a contact on the unit to "up" to ground and shorting a "down" contact to ground to close.)

Anyway we can implement two different pins to control a dual channel relay one to open the garage and another pin to close the garage door, including the sensors?

**Comment by plhyhc** [comment]
Adding a dual channel relay would require some refactoring, but it sounds like a good idea.  I'll review over time to see how best to do this.  The config will need updating, and how the door is triggered will need updating.  Also feel free to fork the project, make some changes and create a pull request.

**Comment by plhyhc** [comment]
@serial8killer Are you still interested in this modification to allow for two separate pins for up and down? I may get some time around the holidays this month.

**Comment by serial8killer** [comment]
Hi @plhyhc , thank you for your availability, but since it wasn't possible, I managed to find another solution using HAA and an ESP. So issue closed, thank you again for your interest.
