### ISSUE TITLE
Security hole with HomePods

### ISSUE THREAD

**Issue by nsayer** [plhyhc/homebridge-garage-door-wsensor#15]
If you ask a HomePod to open the garage door, it will tell you that you must continue on your personal device.

However, if you tell your HomePod to close the garage door (and it's closed), then it will open the door, thinking that it is actually closing it.

Requests for action should be separated between "open" and "close," and an attempt to "close" when the sensor says "closed" should do nothing.

**Comment by plhyhc** [comment]
Nick, this is a good concern. Thank you reporting. I don't have a HomePod but I'll try to replicate with Siri and try to address.

**Comment by plhyhc** [comment]
Thanks again Nick for providing the pull request to resolve this issue.  I did noticed this was also an issue when using Siri on the iPhone.  I have merged it in and published to npmjs.
