### ISSUE TITLE
gpio-admin

### ISSUE THREAD

**Issue by baseship** [plhyhc/homebridge-garage-door-wsensor#2]
In your how to setup - before "make"
the pi-gpio.js file must be updatet.
Change this:
int size = snprintf(path, PATH_MAX, "/sys/devices/virtual/gpio/gpio%u/%s", pin, filename);
To this:
int size = snprintf(path, PATH_MAX, "/sys/class/gpio/gpio%u/%s", pin, filename);

My problem is, after reboot the pin with the relay is on and the garagedoor opens
how can i set the pin off by reboot

**Comment by plhyhc** [comment]
You need to select a pin that is set to LOW on boot according to the
Raspberry Pi schematic.

**Comment by marcgrc** [comment]
My problem is, after reboot the pin with the relay is on and the garagedoor opens
how can i set the pin off by reboot

**Comment by marcgrc** [comment]
In your how to setup - before "make"
the pi-gpio.js file must be updatet.
Change this:
int size = snprintf(path, PATH_MAX, "/sys/devices/virtual/gpio/gpio%u/%s", pin, filename);
To this:
int size = snprintf(path, PATH_MAX, "/sys/class/gpio/gpio%u/%s", pin, filename);

I try but I have always this error 
Can you help me thank

**Comment by marcgrc** [comment]
Help me thanks

**Comment by plhyhc** [comment]
Have you tried the latest version?  It is using a different library to talk to the GPIO pins.

**Comment by marcgrc** [comment]
Yes thank you
