### ISSUE TITLE
Door Relay Pin Always HIGH.

### ISSUE THREAD

**Issue by SK8081** [plhyhc/homebridge-garage-door-wsensor#4]
Running this, when Homebridge starts, the relay PIN goes high.  When I reboot, it cycles the relay and opens the door.  Is there any way to resolve this?

Thanks

**Comment by plhyhc** [comment]
In the config file try setting the key "invertDoorState" to true.

**Comment by SK8081** [comment]
Thanks for the quick reply.  I did.  It didn't work.  What did work was modifying this in index.js

GarageDoorOpener.prototype.gpioDoorVal = function (val) {
	if (this.invertDoorState) val = !val;
	return val ? rpio.**LOW** : rpio.**HIGH**;

I would think this is essentially the same as setting inverted in config.json.  however, that wasn't working for me.

**Comment by plhyhc** [comment]
Awesome.  Glad you were able to figure it out.  I am beginning to wonder if different versions of Raspberry PI set the GPIO pin state differently.  Hope you find this library useful.

**Comment by addek83** [comment]
I had the exact same issue and your fix did the trick :-)  inverteddoorstate did nothing for me too, but swithing low and high in index.js did the trick :-) On to the next step in this really fun project :-)
