### ISSUE TITLE
PIN 11 always active

### ISSUE THREAD

**Issue by DarioP76** [plhyhc/homebridge-garage-door-wsensor#5]
Hello,
raspberry PI 3.
i am using your project by downloading the plugin directly from homebridge, but i have a problem.
Pin 11 is always active (on) and therefore the relay always remains closed. I never have a change of status, can you help me?
Thank you

**Comment by plhyhc** [comment]
There are a couple things you can try.  First in the config.json file change the boolean value of "invertDoorState".  Try true or false to see if that helps.  If that doesn't work, some people have modified the index.js file at line 104, by manually inverting the results.  By changing it to: 
```
return val ? rpio.LOW : rpio.HIGH;
```
Hope that helps.

**Comment by DarioP76** [comment]
Hi,
unfortunately none of the changes work. I had already tried to set the "invertDoorState" value: false, to true, but without changes. By keeping it false, and changing line 104 as you suggested, the effect doesn't change. As soon as the module is started, pin 11 is activated and remains so. I also replaced the reference pin and the problem shifts.  :( 
Thank you so much for your help

**Comment by plhyhc** [comment]
A new feature in the config has been added that may resolve this issue.  "input_pull", and with this along with "invertSensorState" it may work for you.
