### ISSUE TITLE
Issue after reinstall

### ISSUE THREAD

**Issue by wjstone** [plhyhc/homebridge-garage-door-wsensor#8]
I had to reinstall and now I get this everytime I try to config.

TypeError: Invalid arg2
    at bindcall2 (/usr/local/lib/node_modules/homebridge-garage-door-wsensor/node_modules/rpio/lib/rpio.js:119:9)
    at rpio.read (/usr/local/lib/node_modules/homebridge-garage-door-wsensor/node_modules/rpio/lib/rpio.js:892:9)
    at GarageDoorOpener.readSensorState (/usr/local/lib/node_modules/homebridge-garage-door-wsensor/index.js:69:36)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-garage-door-wsensor/index.js:56:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by plhyhc** [comment]
In your config file, what do you have "doorSensorPin" set to?  The error looks to be complaining it is not a valid value.

**Comment by wjstone** [comment]
Heres my config.  {
    "accessory": "Garage Door Opener",
    "name": "Garage Door",
    "doorRelayPin": 3,
    "doorSensorPin": 11,
    "invertDoorState": true,
    "invertSensorState": false,
    "duration_ms": 350
}

**Comment by wjstone** [comment]
Am i correct in thinking that the pin is the actual pin number and not the GPIO number?

**Comment by plhyhc** [comment]
You are correct, it is the actual pin number and not GPIO number.  The value you have looks correct as an integer.  And looking at the pin chart 11 is a valid pin number.

**Comment by wjstone** [comment]
I’ll try it again when I get home


On Jan 18, 2021, at 4:22 PM, Josh Kraft <notifications@github.com<mailto:notifications@github.com>> wrote:



You are correct, it is the actual pin number and not GPIO number. The value you have looks correct as an integer. And looking at the pin chart 11 is a valid pin number.

**Comment by wjstone** [comment]
Tried again.  I've moved to a different pin,  shorted it to ground.  Doesn't seem to matter what I do.

**Comment by plhyhc** [comment]
After reviewing the commits in the node-rpio library, you may want to uninstall and install again.  Yesterday jperkin made some changes to the very lines of code you are experiencing errors on.  Last change was 15 hours ago, so hopefully it has resolved the issue you were experiencing.
https://github.com/jperkin/node-rpio/commit/9789d6ffade71db6419fbb0dfc109e2c39b47af4
also review:
https://github.com/jperkin/node-rpio/commit/55ccd3915787b105e83c378246fa43ef758d3f46

**Comment by wjstone** [comment]
That did it.  Thanks so much.
