### ISSUE TITLE
how change initial state?

### ISSUE THREAD

**Issue by toshibochan** [plhyhc/homebridge-garage-door-wsensor#9]
how change initial state? when Homebridge start the relay stay always on. How I can change initial state when boot to 1?

**Comment by plhyhc** [comment]
You could try setting the "invertDoorState" to true in the homebridge config.

**Comment by toshibochan** [comment]
the problem is the Raspberry pi reboot or Homebridge reboot the relay stay on and relay led stay on on boot. I need the led to stay off on boot.

**Comment by toshibochan** [comment]
"invertDoorState" to true just change how relay behave but still the relay turn on when reboot

**Comment by toshibochan** [comment]
im using 
node v14.16.0
homebridge v1.3.1

**Comment by plhyhc** [comment]
Which PIN number are you using for the relay?

**Comment by toshibochan** [comment]
2 garage door Pin 16 and 18.

**Comment by plhyhc** [comment]
There are some pins that have an "on" state when the raspberry pi boots up. I am not sure which pins they are.  You could try a different pin.  I used pin 11 and it worked for me.
